### ISSUE TITLE
kurdum fakat herhangi bir şey açılmadı

### ISSUE THREAD

**Issue by zafhur** [eminfedar/easyprograminstaller#1]
Selamün aleyküm. kardeş pardus 17.5 xfce kullanıyorum. epi yi kurdum fakat tıklıyorum açılan hiç bir pencere yok. ters giden nedir acaba?

**Comment by eminfedar** [comment]
Bu biraz eski bir program. Birkaç düzenleme yaptım, şimdi çalışır ama, zaten içlerindeki uygulamalar artık kolayca kurulabiliyor distroların sağladığı marketler ile. Yine de denemek isterseniz releases kısmından birazdan .deb dosyasını yayınlayacağım.

**Comment by eminfedar** [comment]
https://github.com/eminfedar/easyprograminstaller/releases/tag/v1.5

Ama dediğim gibi, eski bir program :)

**Comment by zafhur** [comment]
![easy](https://user-images.githubusercontent.com/3587375/54866881-da038480-4d8a-11e9-8d0f-3131318f3181.png)

maalesef böyle bir hata verdi
